type token =
  [ `BEGIN_DEF
  | `BOOL_DEF
  | `CALL_DEF
  | `CLOSE_PAREN_DEF
  | `CLASS_DEF
  | `COMMENT_CHAR_DEF
  | `FALSE_DEF
  | `FIELD_DEF
  | `IF_DEF
  | `INPUT_INT_DEF
  | `INPUT_STRING_DEF
  | `INT_DEF
  | `LET_DEF
  | `MAIN_DEF
  | `METHOD_DEF
  | `ME_DEF
  | `NEW_DEF
  | `NULL_DEF
  | `OPEN_PAREN_DEF
  | `PRINT_DEF
  | `QUOTE_CHAR
  | `RETURN_DEF
  | `SET_DEF
  | `STRING_DEF
  | `TRUE_DEF
  | `VOID_DEF
  | `WHILE_DEF
  | `Identifier of string ]
